config/routes.rb
NestedModel::Application.routes.draw do
  resources :contents

  resources :documents

  root :to => 'documents#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :name
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :name, :sections_attributes
  
  has_many :sections
  
  validates :name, :presence =>  { :message => "Must be filled" }
  
  accepts_nested_attributes_for :sections, :allow_destroy => :true#, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
  attr_accessible :user_id, :section_id, :content_id
  
  belongs_to :section
  belongs_to :content
  
  validates :user_id, :section, :content, :presence =>  { :message => "Must be filled" }
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :name, :content_ids
  
  belongs_to :document
  
  has_many :paragraphs, :dependent => :destroy
  has_many :contents, :through => :paragraphs
  
  validates :name, :presence =>  { :message => "Must be filled" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.all
  end

  def show
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(params[:content])
    if @content.save
      redirect_to @content, :notice => "Successfully created content."
    else
      render :action => 'new'
    end
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])
    if @content.update_attributes(params[:content])
      redirect_to @content, :notice  => "Successfully updated content."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    redirect_to contents_url, :notice => "Successfully destroyed content."
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
    @document.sections.build
  end

  def create
    @document = Document.new(params[:document])
    if @document.save
      redirect_to @document, :notice => "Successfully created document."
    else
      render :action => 'new'
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params[:document])
      redirect_to @document, :notice  => "Successfully updated document."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_url, :notice => "Successfully destroyed document."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/contents/_form.html.erb
<%= form_for @content do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/contents/edit.html.erb
<% title "Edit Content" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @content %> |
  <%= link_to "View All", contents_path %>
</p>

app/views/contents/index.html.erb
<% title "Contents" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for content in @contents %>
    <tr>
      <td><%= content.name %></td>
      <td><%= link_to "Show", content %></td>
      <td><%= link_to "Edit", edit_content_path(content) %></td>
      <td><%= link_to "Destroy", content, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Content", new_content_path %></p>

app/views/contents/new.html.erb
<% title "New Content" %>

<%= render 'form' %>

<p><%= link_to "Back to List", contents_path %></p>

app/views/contents/show.html.erb
<% title "Content" %>

<p>
  <strong>Name:</strong>
  <%= @content.name %>
</p>

<p>
  <%= link_to "Edit", edit_content_path(@content) %> |
  <%= link_to "Destroy", @content, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", contents_path %>
</p>

app/views/documents/_form.html.erb
<%= form_for @document do |f| %>
      <%= f.error_messages %>
   	<div><%= f.label :name, "Document Name" %> &nbsp;&nbsp;&nbsp;<%= f.text_field :name %></div>
   	
   	<%= f.fields_for :sections do |builder| %> 
   		<div><%= f.label :name, "Section Name" %>&nbsp;&nbsp;&nbsp;<%= builder.text_field :name %></div>
   		<div>
   			<%= f.label :content_ids, "Select Content" %>&nbsp;&nbsp;&nbsp;
   			<%= builder.select :content_ids, Content.all.collect {|p| [ p.name, p.id ] },{:prompt => "Please Select"}, {:class => "nhs_select", :multiple => true}  %></div>
   <% end %>
   <%= f.submit :submit%>
<% end %>

app/views/documents/edit.html.erb
<% title "Edit Document" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @document %> |
  <%= link_to "View All", documents_path %>
</p>

app/views/documents/index.html.erb
<% title "Documents" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for document in @documents %>
    <tr>
      <td><%= document.name %></td>
      <td><%= link_to "Show", document %></td>
      <td><%= link_to "Edit", edit_document_path(document) %></td>
      <td><%= link_to "Destroy", document, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Document", new_document_path %></p>

app/views/documents/new.html.erb
<% title "New Document" %>

<%= render 'form' %>

<p><%= link_to "Back to List", documents_path %></p>

app/views/documents/show.html.erb
<% title "Document" %>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <%= link_to "Edit", edit_document_path(@document) %> |
  <%= link_to "Destroy", @document, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", documents_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>